---

- name: install python-mysqldb
  yum:
    name: MySQL-python
    state: present

- name: Set new password to root user
  command: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');"'
  changed_when: false
  tags: passwmysql

- name: install /etc/my.cnf config
  template:
    src: my.cnf.main.j2
    dest: /etc/my.cnf
    mode: 0644
  tags: my_cnf

- name: install ~./my.cnf config
  template:
    src: my.cnf.user.j2
    dest: /root/.my.cnf
    mode: 0400
  tags: my_cnf

- name: change permission /etc/my.cnf.d/
  file:
    dest: /etc/my.cnf.d
    mode: u=rwX,g=rX,o=r
    recurse: true
  tags: my_cnf

- name: root password is present
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password | mandatory }}"
    state: present
  with_items:
    - localhost
  ignore_errors: true

- name: test database is absent
  mysql_db:
    name: test
    state: absent
  when: mysql_remove_test_database

- name: anonymous users are absent
  mysql_user:
    name: ''
    state: absent
    host_all: true
  when: mysql_remove_anonymous_users

- name: copy mysql_remove_remote_root
  copy:
    src: "{{ item }}.sql"
    dest: "/tmp/{{ item }}.sql"
  with_items:
    - mysql_remove_remote_root
  when: mysql_remove_remote_root
  changed_when: false

- name: apply mysql_remove_remote_root
  mysql_db:
    name: mysql
    state: import
    target: "/tmp/{{ item }}.sql"
  with_items:
    - mysql_remove_remote_root
  when: mysql_remove_remote_root
  changed_when: false
