---

pakages:
  - sudo
  - openssh-clients
  - vsftpd
  - scponly
hexausers:
  - {groups: 'wheel', user: 'user1', password: '######'}
  - {groups: 'wheel', user: 'user2', password: '######'}
  - {groups: 'wheel', user: 'user3', password: '######'}
  - {groups: 'wheel', user: 'ansible', password: '######'}
depusers:
  - {groups: 'ftpusers', user: 'fed', shell: '/usr/bin/scponly', home: '/var/www/html', password: '####'}
addgroup:
  - {group: ftpusers}
files:
  - {src: 'sshd_config', dest: '/etc/ssh/', mode: '0644'}
  - {src: 'chmod.sh', dest: '/scripts/', mode: '0755'}
  - {src: 'sudoers', dest: '/etc/', mode: 'u=r,g=r'}
  - {src: 'vsftpd.conf', dest: '/etc/vsftpd/', mode: '0600'}
chk:
  - {name: vsftpd}
  - {name: sshd}
  - {name: crond}
keys:
 - {user: 'user1', key: '#####'}
 - {user: 'user2', key: '#####'}
 - {user: 'user3', key: '#####'}
