---

- name: Create droplet via DigitalOcean
  digital_ocean:
      state: present
      command: droplet
      name: "{{ service_name }}"
      api_token: "#########"
      ssh_key_ids: "#######"
      size_id: s-1vcpu-1gb
      region_id: "{{ do_region }}"
      image_id: centos-7-x64
      wait_timeout: 500
  register: my_droplet
  tags: do_create
- debug: msg="IP is droplet {{ my_droplet.droplet.ip_address }}"
- name: Add droplet ip to inventory file
  add_host: name=droplet ansible_ssh_host="{{ my_droplet.droplet.ip_address }}"
- name: pause 30 seconds
  pause: seconds=30
